routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth']], function () {
	Route::get('cambiar_contrasena','UsuariosController@cambiar_contrasena')->name('cambiar_contrasena');
	Route::post('cambiar_pass','UsuariosController@cambiar_pass')->name('cambiar_pass');
});

Route::group(['middleware' => ['auth', 'activo']], function () {	
	Route::get('/getAgrupamientos/{id}', 'EmpleadoRecategorizacionController@getAgrupamientos')->name('getAgrupamientos');
	Route::get('/getCategorias/{id}', 'EmpleadoRecategorizacionController@getCategorias')->name('getCategorias');

	Route::post('/calcular', 'EmpleadoRecategorizacionController@calcular')->name('empleadoRecategorizacions.calcular');

	Route::get('/descargar_recategorizacion', 'EmpleadoController@descargar_recategorizacion')->name('descargar_recategorizacion');
	Route::get('/imprimir_recategorizacion', 'EmpleadoController@imprimir_recategorizacion')->name('imprimir_recategorizacion');

	Route::resource('empleadoRecategorizacions', 'EmpleadoRecategorizacionController');

	Route::resource('empleados', 'EmpleadoController');

});

Route::group(['middleware' => ['auth', 'activo', 'role:administrador']], function () {

	Route::resource('agrupamientos', 'AgrupamientoController');

	Route::resource('categorias', 'CategoriaController');

	Route::resource('regimens', 'RegimenController');

	Route::resource('localidades', 'LocalidadesController');

	Route::resource('zonas', 'ZonasController');

	Route::resource('zonaLocalidads', 'ZonaLocalidadController');

	Route::resource('titulos', 'TituloController');

	Route::resource('usuarios', 'UsuariosController');

	Route::resource('rols', 'RolController');

	Route::resource('roleUsers', 'Role_UserController');

	Route::resource('usuarioOps', 'UsuarioOpController');

	Route::resource('permisos', 'PermisoController');

	Route::resource('permisoRols', 'PermisoRolController');

	Route::get('buscar_usuario', 'UsuariosController@buscar_usuario')->name('buscar_usuario');
	Route::get('buscar_usuario_resetear', 'UsuariosController@buscar_usuario_resetear')->name('buscar_usuario_resetear');
	
	Route::get('resetear_contrasena/{id}', 'UsuariosController@resetear_contrasena')->name('resetear_contrasena');

	Route::resource('provincias', 'ProvinciaController');

});

app/Models/Empleado.php
<?php

namespace App\Models;

use Eloquent as Model;
use Illuminate\Database\Eloquent\SoftDeletes;

/**
 * Class Empleado
 * @package App\Models
 * @version October 15, 2019, 2:21 pm UTC
 *
 * @property string apynom
 * @property integer nro_dni
 * @property string nro_cuil
 * @property integer nro_legajo
 */
class Empleado extends Model
{
    use SoftDeletes;

    public $table = 'empleados';
    
    const CREATED_AT = 'created_at';
    const UPDATED_AT = 'updated_at';


    protected $dates = ['deleted_at'];


    public $fillable = [
        'apynom',
        'nro_dni',
        'nro_expediente',
        'nro_legajo'
    ];

    /**
     * The attributes that should be casted to native types.
     *
     * @var array
     */
    protected $casts = [
        'id' => 'integer',
        'apynom' => 'string',
        'nro_dni' => 'integer',
        'nro_expediente' => 'string',
        'nro_legajo' => 'integer'
    ];

    /**
     * Validation rules
     *
     * @var array
     */
    public static $rules = [
        'apynom' => 'required',
        'nro_dni' => 'required'
        /*'nro_expediente' => 'required',
        'nro_legajo' => 'required'*/
    ];

    
}

app/Http/Controllers/EmpleadoController.php
<?php

namespace App\Http\Controllers;



 
use App\Http\Requests\CreateEmpleadoRequest;
use App\Http\Requests\UpdateEmpleadoRequest;
use App\Repositories\EmpleadoRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;

use PDF;
use Dompdf\Adapter\CPDF;
use Dompdf\Dompdf;
use Dompdf\Exception;

use App\Models\Empleado;
use App\Models\EmpleadoRecategorizacion;

class EmpleadoController extends AppBaseController
{
    /** @var  EmpleadoRepository */
    private $empleadoRepository;

    public function __construct(EmpleadoRepository $empleadoRepo)
    {
        $this->empleadoRepository = $empleadoRepo;
    }

    /**
     * Display a listing of the Empleado.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $empleados = $this->empleadoRepository->all();

        return view('empleados.index')
            ->with('empleados', $empleados);
    }

    /**
     * Show the form for creating a new Empleado.
     *
     * @return Response
     */
    public function create(Request $request)
    {   
        $datos = $request->all();
        return view('empleados.create')->with('datos',$datos);
    }

    /**
     * Store a newly created Empleado in storage.
     *
     * @param CreateEmpleadoRequest $request
     *
     * @return Response
     */
    public function store(CreateEmpleadoRequest $request)
    {   
        $id_user = auth()->user()->id;
        $input = $request->all();
        $datos_empleado = ['apynom' => $input['apynom'],
                            'nro_dni' => $input['nro_dni'],
                            'nro_expediente' => $input['nro_expediente'],
                            'nro_legajo' => $input['nro_legajo']
                            ];

        $empleado = $this->empleadoRepository->create($datos_empleado);


        $id_empleado = Empleado::select('id')
                                ->where('nro_dni',$input['nro_dni'])
                                ->orderby('id','desc')
                                ->first();

        if(!isset($input['id_localidad_trabaja'])){
            $input['id_localidad_trabaja'] = null;
            if(!isset($input['id_titulo'])){
                $input['id_titulo'] = null;
            }
        }
        else{
            $input['id_titulo'] = null;
            $input['tiene_capacitacion']= null;
        }

        $datos_empl_rec = [ 'id_categoria_inicial' => $input['id_categoria_inicial'],
                            'id_categoria_ascenso' => $input['id_categoria_ascenso'],
                            'fecha_inicial'  => $input['fecha_inicial'],
                            'fecha_final'  => $input['fecha_final'],
                            'fecha_ascenso' => $input['fecha_ascenso'],
                            'id_localidad_trabaja' => $input['id_localidad_trabaja'],
                            'id_titulo' => $input['id_titulo'],
                            'tiene_capacitacion' => $input['tiene_capacitacion'],
                            'id_empleado' => $id_empleado->id,
                            'id_user' => $id_user
                            ];
        EmpleadoRecategorizacion::create($datos_empl_rec);

        Flash::success('Cálculo guardaro Correctamente.');

        return redirect(route('empleadoRecategorizacions.index'));
    }

    /**
     * Display the specified Empleado.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $empleado = $this->empleadoRepository->find($id);
        $empleadoRecategorizacion = EmpleadoRecategorizacion::where('id_empleado',$empleado->id)->first();
        
        if (empty($empleado)) {
            Flash::error('Empleado not found');

            return redirect(route('empleados.index'));
        }

        return view('empleados.show')->with('empleado', $empleado)
                        ->with('empleadoRecategorizacion',$empleadoRecategorizacion);
    }

    /**
     * Show the form for editing the specified Empleado.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $empleado = $this->empleadoRepository->find($id);
        $empleadoRecategorizacion = EmpleadoRecategorizacion::where('id_empleado',$empleado->id)->first();
        if (empty($empleado)) {
            Flash::error('Empleado not found');

            return redirect(route('empleados.index'));
        }

        return view('empleados.edit')->with('empleado', $empleado)->with('empleadoRecategorizacion',$empleadoRecategorizacion);
    }

    /**
     * Update the specified Empleado in storage.
     *
     * @param int $id
     * @param UpdateEmpleadoRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateEmpleadoRequest $request)
    {
        $empleado = $this->empleadoRepository->find($id);
        $empleadoRecategorizacion = EmpleadoRecategorizacion::where('id_empleado', $id)->first();

        if (empty($empleado)) {
            Flash::error('Empleado not found');

            return redirect(route('empleados.index'));
        }

        $empleado = $this->empleadoRepository->update($request->all(), $id);

        Flash::success('Empleado updatedCorrectamente.');

        return redirect(route('empleadoRecategorizacions.edit', $empleadoRecategorizacion->id));
    }

    /**
     * Remove the specified Empleado from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $empleado = $this->empleadoRepository->find($id);
        
        $empleadoRecategorizacion = EmpleadoRecategorizacion::where('id_empleado',$empleado->id)->first();
        
        EmpleadoRecategorizacion::destroy($empleadoRecategorizacion->id);


        if (empty($empleado)) {
            Flash::error('Empleado no encontrado');

            return redirect(route('empleados.index'));
        }

        $this->empleadoRepository->delete($id);

        Flash::success('Cálculo eliminado Correctamente.');

        return redirect(route('empleadoRecategorizacions.index'));
    }

    /**********************************************************************/
    /***************PDF****************************************************/
    /**********************************************************************/

    private function obtener_recategorizacion($id){
        $recategorizacion = EmpleadoRecategorizacion::where('id',$id)->first();
        $data['recategorizacion'] = $recategorizacion;
        //dd($data);
        $pdf = PDF::loadView('/empleados/recategorizacion_pdf', $data);
        return $pdf;
        
    }

    public function descargar_recategorizacion(Request $request){
        $id = $request->id_emp_rec;
        $pdf = $this->obtener_recategorizacion($id);
        $download = $pdf->download("Recategorización N° $id.pdf");
        return $download;
    }
    public function imprimir_recategorizacion(Request $request){
        $id = $request->id_emp_rec;
        $pdf = $this->obtener_recategorizacion($id);
        $download = $pdf->stream("Recategorización N° $id.pdf");
        return $download;
    }
}

resources/views/empleados/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Guardar Cálculo
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'empleados.store']) !!}
                        
                        @include('empleados.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/empleados/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Datos Empleado
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($empleado, ['route' => ['empleados.update', $empleado->id], 'method' => 'patch']) !!}

                        @include('empleados.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/empleados/fields.blade.php
                        {!! Form::hidden('id_categoria_inicial', $empleadoRecategorizacion['id_categoria_inicial'], ['class' => 'form-control']) !!}

                        {!! Form::hidden('id_categoria_ascenso', $empleadoRecategorizacion['id_categoria_ascenso'], ['class' => 'form-control', 'readonly' => '']) !!}

                        {!! Form::hidden('fecha_inicial', $empleadoRecategorizacion['fecha_inicial']) !!}

                        {!! Form::hidden('fecha_ascenso', $empleadoRecategorizacion['fecha_ascenso']) !!}

                        {!! Form::hidden('fecha_final', $empleadoRecategorizacion['fecha_final']) !!}

                        @if(isset($empleadoRecategorizacion['id_localidad_trabaja']))
                        {!! Form::hidden('id_localidad_trabaja', $empleadoRecategorizacion['id_localidad_trabaja'], ['class' => 'form-control', 'readonly' => '']) !!}
                        @else
                        {!! Form::hidden('id_localidad_trabaja', null, ['class' => 'form-control', 'readonly' => '']) !!}
                        @endif


                        @if(isset($empleadoRecategorizacion['titulo']))
                        {!! Form::hidden('id_titulo', $empleadoRecategorizacion['id_titulo'], ['class' => 'form-control', 'readonly' => '']) !!}
                        @else
                        {!! Form::hidden('id_titulo', null, ['class' => 'form-control', 'readonly' => '']) !!}
                        @endif

                        @if(isset($empleadoRecategorizacion['tiene_capacitacion']))
                        {!! Form::hidden('tiene_capacitacion', $empleadoRecategorizacion['tiene_capacitacion'], ['class' => 'form-control', 'readonly' => '']) !!}
                        @else
                        {!! Form::hidden('tiene_capacitacion', null, ['class' => 'form-control', 'readonly' => '']) !!}
                        @endif


<div class="col-sm-12">
    <h3>Datos del Empleado</h3>
</div>
<!-- Apynom Field -->
<div class="form-group col-sm-6"> 
    {!! Form::label('apynom', 'Apellido y Nombres:') !!}
    {!! Form::text('apynom', null, ['class' => 'form-control', 'required']) !!}
</div>

<!-- Nro Dni Field -->
<div class="form-group col-sm-6">
    {!! Form::label('nro_dni', 'Nro de Documento:') !!}
    {!! Form::number('nro_dni', null, ['class' => 'form-control', 'required']) !!}
</div>

<!-- Nro Cuil Field -->
<div class="form-group col-sm-6">
    {!! Form::label('nro_expediente', 'Nro de  Expediente:') !!}
    {!! Form::text('nro_expediente', null, ['class' => 'form-control']) !!}
</div>

<!-- Nro Legajo Field -->
<div class="form-group col-sm-6">
    {!! Form::label('nro_legajo', 'Nro de Legajo:') !!}
    {!! Form::number('nro_legajo', null, ['class' => 'form-control']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12 text-center">
    <hr>
    {!! Form::submit('Guardar', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('empleados.index') !!}" class="btn btn-default">Cancelar</a>
</div>

resources/views/empleados/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Empleados</h1>
        <h1 class="pull-right">
           <a class="btn btn-success pull-right" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('empleadoRecategorizacions.create') !!}">Nuevo Cálculo</a>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('empleados.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/empleados/recategorizacion_pdf.blade.php
<!DOCTYPE html>
<html>
<head>
	<title>Recategorización N° {{$recategorizacion->id}}</title>

	<style>
    	body{
     		font-size: 12pt; 
     		font-family: 'Times New Roman', Times;
     		margin: 70px;
    	}
    	#customers {
		  width: 100%;
		  font-size: 10pt;
		}
		#customers td, #customers th {
		  border: 1px solid #ddd;
		}
		#customers th {
		  text-align: left;
		  background-color: lightgrey;
		}
		.der{
		    text-align: right;
		}
		.izq{
			text-align: left;
		}
		.center{
			text-align: center;
		}
		.recuadro{
			border: 1px lightgrey solid;
			padding: 20px;
		}
	</style>
</head>
<body>
	<div class="recuadro">
		<h3 style=" text-transform: uppercase;">{{$recategorizacion->Empleado->apynom}}</h3>
		
		<table id="customers">
			<tr>
				<th style="width: 40%">NRO DE DOCUMENTO</th>
				<td>{{$recategorizacion->Empleado->nro_dni}}</td>
			</tr>
			<tr>
				<th style="width: 40%">NRO DE EXPEDIENTE</th>
				<td>{{$recategorizacion->Empleado->nro_expediente}}</td>
			</tr>
			<tr>
				<th style="width: 40%">NRO DE LEGAJO</th>
				<td>{{$recategorizacion->Empleado->nro_legajo}}</td>
			</tr>
			@if($recategorizacion->Categoria_inicial->Agrupamiento->Regimen->id == 2)
				@if($recategorizacion->Categoria_inicial->Agrupamiento->id == 3 OR $recategorizacion->Categoria_inicial->Agrupamiento->id == 6)
				<tr>
					<th style="width: 40%">TITULO</th>
					<td>{{$recategorizacion->Titulo->descripcion}}</td>
				</tr>
				@endif
			
				<tr>
					<th style="width: 40%">TIENE CAPACITACIÓN</th>
					<td>@if($recategorizacion->tiene_capacitacion) Si @else No @endif</td>
				</tr>
			@endif
			@if($recategorizacion->Categoria_inicial->Agrupamiento->Regimen->id == 3)
			<tr>
				<th style="width: 40%">LOCALIDAD TRABAJA</th>
				<td>{{$recategorizacion->Localidad->descripcion}}</td>
			</tr>
			@endif			
		</table>
		<br>
		<table id="customers">
			<tr>
				<th style="width: 40%">RÉGIMEN LABORAL</th>
				<td>{{$recategorizacion->Categoria_inicial->Agrupamiento->Regimen->descripcion}}</td>
			</tr>
			<tr>
				<th style="width: 40%">AGRUPAMIENTO</th>
				<td>{{$recategorizacion->Categoria_inicial->Agrupamiento->desc_agrup}}</td>
			</tr>
		</table>
		<br>
		<table id="customers">
			<tr>
				<th style="width: 40%">CATEGORÍA INICIAL</th>
				<td>{{$recategorizacion->Categoria_inicial->descripcion}}</td>
			</tr>
			<tr>
				<th style="width: 40%">FECHA INICIAL</th>
				<td>{{date('d/m/Y',strtotime($recategorizacion->fecha_inicial))}}</td>
			</tr>
		</table>
		<br>
		<table id="customers">
			<tr>
				<th style="width: 40%">CATEGORÍA ASCENSO</th>
				<td>{{$recategorizacion->Categoria_ascenso->descripcion}}</td>
			</tr>
			<tr>
				<th style="width: 40%">FECHA COMPUTO</th>
				<td>{{date('d/m/Y',strtotime($recategorizacion->fecha_ascenso))}}</td>
			</tr>
		</table>

		<p>Usuario: {{$recategorizacion->User->name}}</p>
	</div>
</body>
</html>

resources/views/empleados/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left" style="text-transform: uppercase;">{{$empleadoRecategorizacion->Empleado->apynom}}</h1>
        <h1 class="pull-right">
            {!! Form::open(['route' => ['empleados.destroy', $empleadoRecategorizacion->id_empleado], 'method' => 'delete']) !!}
            <button type="submit" class="btn btn-danger pull-right" style="margin-top: -10px;
            margin-bottom: 5px; margin-left: 5px;" onclick = "return confirm('Esta Seguro?')">Eliminar</button>
            {!! Form::close() !!}
        </h1>
        <h1 class="pull-right">
            <form action="{!! route('descargar_recategorizacion') !!}" method="GET" target="_blank">
                <input type="hidden" name="id_emp_rec" id="id_emp_rec" value="{{$empleadoRecategorizacion->id}}">
                <button type="submit" class="btn btn-success pull-right" style="margin-top: -10px;margin-bottom: 5px; margin-left: 5px;">Descargar</button>
            </form>
        </h1>
        <h1 class="pull-right">
            <form action="{!! route('imprimir_recategorizacion') !!}" method="GET" target="_blank">
                <input type="hidden" name="id_emp_rec" id="id_emp_rec" value="{{$empleadoRecategorizacion->id}}">
                <button type="submit" class="btn btn-info pull-right" style="margin-top: -10px;margin-bottom: 5px; margin-left: 5px;">Imprimir</button>
            </form>
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('empleados.show_fields')
                    <a href="{!! route('empleadoRecategorizacions.index') !!}" class="btn btn-default">Volver</a>
                     
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/empleados/show_fields.blade.php
<div class="col-sm-12" style="padding-top: 20px; padding-right: 20px;">
<table class="table table-bordered table-striped" style="text-transform: uppercase;">
    <tr>
        <th>Nro de Documento</th>
        <td>{{$empleado->nro_dni}}</td>
    </tr>
    <tr>
        <th>Nro de Expediente</th>
        <td>{{$empleado->nro_expediente}}</td>
    </tr>
    <tr>
        <th>Nro de Legajo</th>
        <td>{{$empleado->nro_legajo}}</td>
    </tr>
    @if($empleadoRecategorizacion->Categoria_inicial->Agrupamiento->Regimen->id == 2)
        @if($empleadoRecategorizacion->Categoria_inicial->Agrupamiento->id == 3 OR $empleadoRecategorizacion->Categoria_inicial->Agrupamiento->id == 6)
        <tr>
            <th style="width: 40%">TITULO</th>
            <td>{{$empleadoRecategorizacion->Titulo->descripcion}}</td>
            </tr>
        @endif
        <tr>
        <th style="width: 40%">TIENE CAPACITACIÓN</th>
            <td>@if($empleadoRecategorizacion->tiene_capacitacion) Si @else No @endif</td>
        </tr>
    @endif

    @if($empleadoRecategorizacion->Categoria_inicial->Agrupamiento->Regimen->id == 3)
    <tr>
        <th style="width: 40%">LOCALIDAD TRABAJA</th>
        <td>{{$empleadoRecategorizacion->Localidad->descripcion}}</td>
    </tr>
    @endif
</table>
</div>

<div class="col-sm-12" style="padding-top: 20px; padding-right: 20px;">
    <table class="table table-bordered table-striped" >
        <tr>
                <th style="width: 40%">RÉGIMEN LABORAL</th>
                <td>{{$empleadoRecategorizacion->Categoria_inicial->Agrupamiento->Regimen->descripcion}}</td>
            </tr>
            <tr>
                <th style="width: 40%">AGRUPAMIENTO</th>
                <td>{{$empleadoRecategorizacion->Categoria_inicial->Agrupamiento->desc_agrup}}</td>
            </tr>
        </table>
        <br>
        <table class="table table-bordered table-striped">
            <tr>
                <th style="width: 40%">CATEGORÍA INICIAL</th>
                <td>{{$empleadoRecategorizacion->Categoria_inicial->descripcion}}</td>
            </tr>
            <tr>
                <th style="width: 40%">FECHA INICIAL</th>
                <td>{{date('d/m/Y',strtotime($empleadoRecategorizacion->fecha_inicial))}}</td>
            </tr>
        </table>
        <br>
        <table class="table table-bordered table-striped">
            <tr>
                <th style="width: 40%">CATEGORÍA ASCENSO</th>
                <td>{{$empleadoRecategorizacion->Categoria_ascenso->descripcion}}</td>
            </tr>
            <tr>
                <th style="width: 40%">FECHA COMPUTO</th>
                <td>{{date('d/m/Y',strtotime($empleadoRecategorizacion->fecha_ascenso))}}</td>
            </tr>
</table>
</div>

<div class="col-sm-12">
	<hr>
	<p><b>Usuario:</b> {{$empleadoRecategorizacion->User->name}}</p>
	<hr>
</div>

resources/views/empleados/table.blade.php
<div class="table-responsive">
    <table class="table" id="empleados-table">
        <thead>
            <tr>
                <th>Apellido y Nombres</th>
                <th>Nro Dni</th>
                <th>Nro Cuil</th>
                <th>Nro Legajo</th>
                <th colspan="3">Acciones</th>
            </tr>
        </thead>
        <tbody>
        @foreach($empleados as $empleado)
            <tr>
                <td>{!! $empleado->apynom !!}</td>
                <td>{!! $empleado->nro_dni !!}</td>
                <td>{!! $empleado->nro_cuil !!}</td>
                <td>{!! $empleado->nro_legajo !!}</td>
                <td>
                    {!! Form::open(['route' => ['empleados.destroy', $empleado->id], 'method' => 'delete']) !!}
                        <a href="{!! route('empleados.show', [$empleado->id]) !!}" class='btn btn-info btn-block btn-xs'>Ver</a>
                        {!! Form::button('Eliminar', ['type' => 'submit', 'class' => 'btn btn-block btn-xs btn-danger', 'onclick' => "return confirm('Esta Seguro?')"]) !!}
                        {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>