routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth']], function () {
	Route::get('cambiar_contrasena','UsuariosController@cambiar_contrasena')->name('cambiar_contrasena');
	Route::post('cambiar_pass','UsuariosController@cambiar_pass')->name('cambiar_pass');
});

Route::group(['middleware' => ['auth', 'activo']], function () {	
	Route::get('/getAgrupamientos/{id}', 'EmpleadoRecategorizacionController@getAgrupamientos')->name('getAgrupamientos');
	Route::get('/getCategorias/{id}', 'EmpleadoRecategorizacionController@getCategorias')->name('getCategorias');

	Route::post('/calcular', 'EmpleadoRecategorizacionController@calcular')->name('empleadoRecategorizacions.calcular');

	Route::get('/descargar_recategorizacion', 'EmpleadoController@descargar_recategorizacion')->name('descargar_recategorizacion');
	Route::get('/imprimir_recategorizacion', 'EmpleadoController@imprimir_recategorizacion')->name('imprimir_recategorizacion');

	Route::resource('empleadoRecategorizacions', 'EmpleadoRecategorizacionController');

	Route::resource('empleados', 'EmpleadoController');

});

Route::group(['middleware' => ['auth', 'activo', 'role:administrador']], function () {

	Route::resource('agrupamientos', 'AgrupamientoController');

	Route::resource('categorias', 'CategoriaController');

	Route::resource('regimens', 'RegimenController');

	Route::resource('localidades', 'LocalidadesController');

	Route::resource('zonas', 'ZonasController');

	Route::resource('zonaLocalidads', 'ZonaLocalidadController');

	Route::resource('titulos', 'TituloController');

	Route::resource('usuarios', 'UsuariosController');

	Route::resource('rols', 'RolController');

	Route::resource('roleUsers', 'Role_UserController');

	Route::resource('usuarioOps', 'UsuarioOpController');

	Route::resource('permisos', 'PermisoController');

	Route::resource('permisoRols', 'PermisoRolController');

	Route::get('buscar_usuario', 'UsuariosController@buscar_usuario')->name('buscar_usuario');
	Route::get('buscar_usuario_resetear', 'UsuariosController@buscar_usuario_resetear')->name('buscar_usuario_resetear');
	
	Route::get('resetear_contrasena/{id}', 'UsuariosController@resetear_contrasena')->name('resetear_contrasena');

	Route::resource('provincias', 'ProvinciaController');

});

resources/views/role__users/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Crear Roles Usuario
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'roleUsers.store']) !!}

                        @include('role__users.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/role__users/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Editar Roles  Usuario
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($roleUser, ['route' => ['roleUsers.update', $roleUser->id], 'method' => 'patch']) !!}

                        @include('role__users.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/role__users/fields.blade.php
<!-- User Id Field -->

<div class="form-group col-sm-4">
@if($btn == 'crear')
    {!! Form::label('user_id', 'Usuario:') !!}
    {!! Form::select('user_id', $usuarios, null, ['class' => 'form-control', 'placeholder' => 'Seleccionar','required' => 'true']) !!}
@else
	{!! Form::label('user_id', 'Usuario:') !!}
	<br>{!! $roleUser->usuario->usuario !!}
@endif
</div>

<!-- Role Id Field -->
<div class="form-group col-sm-4">
    {!! Form::label('role_id', 'Rol:') !!}
    {!! Form::select('role_id', $roles, null, ['class' => 'form-control', 'placeholder' => 'Seleccionar']) !!}
</div>
<!-- Submit Field -->
<div class="form-group col-sm-4 text-center">
	<br>    {!! Form::submit('Guardar', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('roleUsers.index') !!}" class="btn btn-default">Cancelar</a>
</div>

resources/views/role__users/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Roles-Usuarios</h1>
        <h1 class="pull-right">
          
        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('role__users.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/role__users/resultado.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Roles-Usuarios</h1>
        
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
            <div class="box box-primary">
                <div class="box-body">

                    <form action="{!! route('buscar_usuario_rol') !!}" method="GET" class="sidebar-form">
                                <div class="input-group">
                                   <input type="text" name="busqueda" class="form-control" placeholder="Buscar por Rol, Usuario, DNI o Apellido y Nombre"/>
                              <span class="input-group-btn">
                                <button type='submit' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i>
                                </button>
                              </span>
                                </div>
                            </form>

                    <div class="table-responsive">
                        <table class="table" id="roleUsers-table">
                            <thead>
                                <tr>
                                    <th>Usuario</th>
                                    <th>Rol</th>
                                    <th colspan="3">Acción</th>
                                </tr>
                            </thead>
                            <tbody>
                            @foreach($roleUsers as $roleUser)
                                <tr>
                                    <td>{!! $roleUser->name !!}</td>
                                    <td>{!! $roleUser->description !!}</td>
                                    <td>
                                        {!! Form::open(['route' => ['roleUsers.destroy', $roleUser->id], 'method' => 'delete']) !!}
                                            <a href="{!! route('roleUsers.show', [$roleUser->id]) !!}" class='btn btn-success btn-xs'><i class="fa fa-eye"></i></a>
                                            <a href="{!! route('roleUsers.edit', [$roleUser->id]) !!}" class='btn btn-primary btn-xs'><i class="fa fa-edit"></i></a>
                                            {!! Form::button('<i class="fa fa-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('¿Está seguro?')"]) !!}
                                        {!! Form::close() !!}
                                    </td>
                                </tr>
                            @endforeach
                            </tbody>
                        </table>
                    </div>
                    </div>
        </div>

        <div class="text-center">
        
        </div>
        {{ $roleUsers->links() }}

    </div>
@endsection

resources/views/role__users/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Role  User
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('role__users.show_fields')
                    <a href="{!! route('roleUsers.index') !!}" class="btn btn-default">Volver</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/role__users/show_fields.blade.php
<!-- Role Id Field -->
<div class="form-group">
    {!! Form::label('role_id', 'Rol:') !!}
    <p>{!! $roleUser->rol->name !!}</p>
</div>

<!-- User Id Field -->
<div class="form-group">
    {!! Form::label('user_id', 'Usuario:') !!}
    <p>{!! $roleUser->usuario->name !!}</p>
</div>

resources/views/role__users/table.blade.php
<form action="{!! route('buscar_usuario_rol') !!}" method="GET" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="busqueda" class="form-control" placeholder="Buscar por Rol, Usuario, DNI o Apellido y Nombre"/>
          <span class="input-group-btn">
            <button type='submit' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i>
            </button>
          </span>
            </div>
        </form>

<div class="table-responsive">
    <table class="table" id="roleUsers-table">
        <thead>
            <tr>
                <th>Usuario</th>
                <th>Rol</th>
                <th colspan="3">Acción</th>
            </tr>
        </thead>
        <tbody>
        @foreach($roleUsers as $roleUser)
            <tr>
                <td>{!! $roleUser->usuario->name !!}</td>
                <td>{!! $roleUser->rol->description !!}</td>
                <td>
                    {!! Form::open(['route' => ['roleUsers.destroy', $roleUser->id], 'method' => 'delete']) !!}
                        <a href="{!! route('roleUsers.show', [$roleUser->id]) !!}" class='btn btn-success btn-xs'><i class="fa fa-eye"></i></a>
                        <a href="{!! route('roleUsers.edit', [$roleUser->id]) !!}" class='btn btn-primary btn-xs'><i class="fa fa-edit"></i></a>
                        {!! Form::button('<i class="fa fa-trash"></i>', ['type' => 'submit', 'class' => 'btn btn-danger btn-xs', 'onclick' => "return confirm('¿Está seguro?')"]) !!}
                    {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>
</div>
{{ $roleUsers->links() }}