routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth']], function () {
	Route::get('cambiar_contrasena','UsuariosController@cambiar_contrasena')->name('cambiar_contrasena');
	Route::post('cambiar_pass','UsuariosController@cambiar_pass')->name('cambiar_pass');
});

Route::group(['middleware' => ['auth', 'activo']], function () {	
	Route::get('/getAgrupamientos/{id}', 'EmpleadoRecategorizacionController@getAgrupamientos')->name('getAgrupamientos');
	Route::get('/getCategorias/{id}', 'EmpleadoRecategorizacionController@getCategorias')->name('getCategorias');

	Route::post('/calcular', 'EmpleadoRecategorizacionController@calcular')->name('empleadoRecategorizacions.calcular');

	Route::get('/descargar_recategorizacion', 'EmpleadoController@descargar_recategorizacion')->name('descargar_recategorizacion');
	Route::get('/imprimir_recategorizacion', 'EmpleadoController@imprimir_recategorizacion')->name('imprimir_recategorizacion');

	Route::resource('empleadoRecategorizacions', 'EmpleadoRecategorizacionController');

	Route::resource('empleados', 'EmpleadoController');

});

Route::group(['middleware' => ['auth', 'activo', 'role:administrador']], function () {

	Route::resource('agrupamientos', 'AgrupamientoController');

	Route::resource('categorias', 'CategoriaController');

	Route::resource('regimens', 'RegimenController');

	Route::resource('localidades', 'LocalidadesController');

	Route::resource('zonas', 'ZonasController');

	Route::resource('zonaLocalidads', 'ZonaLocalidadController');

	Route::resource('titulos', 'TituloController');

	Route::resource('usuarios', 'UsuariosController');

	Route::resource('rols', 'RolController');

	Route::resource('roleUsers', 'Role_UserController');

	Route::resource('usuarioOps', 'UsuarioOpController');

	Route::resource('permisos', 'PermisoController');

	Route::resource('permisoRols', 'PermisoRolController');

	Route::get('buscar_usuario', 'UsuariosController@buscar_usuario')->name('buscar_usuario');
	Route::get('buscar_usuario_resetear', 'UsuariosController@buscar_usuario_resetear')->name('buscar_usuario_resetear');
	
	Route::get('resetear_contrasena/{id}', 'UsuariosController@resetear_contrasena')->name('resetear_contrasena');

	Route::resource('provincias', 'ProvinciaController');

});

resources/views/layouts/app.blade.php
<!DOCTYPE html>
<html>
<head>
    <meta charset="UTF-8">
    <title>Recategorización | Función Pública</title>
    <link rel="icon" type="image/png" href="{{asset('images/icono.png')}}">
    
    <!--link rel="stylesheet" href="{{asset('css/bootstrap.min.css')}}"-->

    <meta content='width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no' name='viewport'>
    <!--menu desplegable-->
    <link rel="stylesheet" href="{{asset('css/menu_desplegable.css')}}">

    <!-- Bootstrap 3.3.7 -->
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css">
    <link rel="stylesheet" href="{{asset('css/bootstrap.min.css')}}">

    <link rel="stylesheet" href="https://gitcdn.github.io/bootstrap-toggle/2.2.2/css/bootstrap-toggle.min.css">
    <link rel="stylesheet" href="{{asset('css/bootstrap-toggle.min.css')}}">
    
    <!-- Font Awesome -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.min.css">
    <!--link rel="stylesheet" href="{{asset('css/font-awesome.min.css')}}"-->

    <!-- Theme style -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/2.4.3/css/AdminLTE.min.css">
    <link rel="stylesheet" href="{{asset('css/AdminLTE.min.css')}}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/2.4.3/css/skins/_all-skins.min.css">
    <link rel="stylesheet" href="{{asset('css/_all-skins.min.css')}}">

    <!-- iCheck -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/iCheck/1.0.2/skins/square/_all.css">
    <link rel="stylesheet" href="{{asset('css/_all.css')}}">

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.5/css/select2.min.css">
    <link rel="stylesheet" href="{{asset('css/select2.min.css')}}">

    <!-- Ionicons -->
    <link rel="stylesheet" href="https://code.ionicframework.com/ionicons/2.0.1/css/ionicons.min.css">
    <link rel="stylesheet" href="{{asset('css/ionicons.min.css')}}">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.7.14/css/bootstrap-datetimepicker.min.css">
    <link rel="stylesheet" href="{{asset('css/bootstrap-datetimepicker.min.css')}}">
    
    <link rel="stylesheet" href="{{asset('css/styles.css')}}">

    
    @yield('css')
    @section('scripts')
    <script type="text/javascript" src="{{asset('js/ajax.js')}}"></script>
    <script type="text/javascript" src="{{asset('js/main.js')}}"></script>
    <script src="http://momentjs.com/downloads/moment.min.js"></script>
    @endsection
</head>

<body class="skin-blue sidebar-mini">
@if (!Auth::guest())
    <div class="wrapper">
        <!-- Main Header -->
        <header class="main-header">

            <!-- Logo -->
            <a href="{{route('home')}}" class="logo">
                <img src="{{asset('images/funcion_publica.png')}}" width="80%">
            </a>

            <!-- Header Navbar -->
            <nav class="navbar navbar-static-top" role="navigation">
                <!-- Sidebar toggle button-->
                <a href="#" class="sidebar-toggle" data-toggle="push-menu" role="button">
                    <span class="sr-only">Toggle navigation</span>
                </a>
                <!-- Navbar Right Menu -->
                <div class="navbar-custom-menu">
                    <ul class="nav navbar-nav">
                        <!-- User Account Menu -->
                        <li class="dropdown user user-menu">
                            <!-- Menu Toggle Button -->
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
                                <!-- The user image in the navbar-->
                                <img src="{{asset('images/user.png')}}"
                                     class="user-image" alt="User Image"/>
                                <!-- hidden-xs hides the username on small devices so only the image appears. -->
                                <span class="hidden-xs">{!! Auth::user()->name !!}</span>
                            </a>
                            <ul class="dropdown-menu">
                                <!-- The user image in the menu -->
                                <li class="user-header">
                                    <img src="{{asset('images/user.png')}}"
                                         class="img-circle" alt="User Image"/>
                                    <p>
                                        {!! Auth::user()->name !!}
                                        
                                    </p>
                                </li>
                                <!-- Menu Footer-->
                                <li class="user-footer">
                                    <div class="pull-left">
                                        <a href="#" class="btn btn-default btn-flat">Cambiar Contraseña</a>
                                    </div>
                                    <div class="pull-right">
                                        <a href="{!! url('/logout') !!}" class="btn btn-default btn-flat"
                                            onclick="event.preventDefault(); document.getElementById('logout-form').submit();">
                                            Salir
                                        </a>
                                        <form id="logout-form" action="{{ url('/logout') }}" method="POST" style="display: none;">
                                            {{ csrf_field() }}
                                        </form>
                                    </div>
                                </li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </nav>
        </header>

        <!-- Left side column. contains the logo and sidebar -->
        @include('layouts.sidebar')
        <!-- Content Wrapper. Contains page content -->
        <div class="content-wrapper">
            @yield('content')
        </div>

        <!-- Main Footer -->
        <footer class="main-footer" style="max-height: 100px;text-align: center">
            <strong>2019 <a href="#">Secretaría de la Función Pública</a>.</strong> Río Negro
        </footer>

    </div>
@else
    <nav class="navbar navbar-default navbar-static-top">
        <div class="container">
            <div class="navbar-header">

                <!-- Collapsed Hamburger -->
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target="#app-navbar-collapse">
                    <span class="sr-only">Toggle Navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>

                <!-- Branding Image -->
                <a class="navbar-brand" href="{!! url('/') !!}">
                    Recategorización
                </a>
            </div>

            <div class="collapse navbar-collapse" id="app-navbar-collapse">
                <!-- Left Side Of Navbar -->
                <ul class="nav navbar-nav">
                    <li><a href="{!! url('/home') !!}">Home</a></li>
                </ul>

                <!-- Right Side Of Navbar -->
                <ul class="nav navbar-nav navbar-right">
                    <!-- Authentication Links -->
                    <li><a href="{!! url('/login') !!}">Login</a></li>
                    <li><a href="{!! url('/register') !!}">Register</a></li>
                </ul>
            </div>
        </div>
    </nav>

    <div id="page-content-wrapper">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    @yield('content')
                </div>
            </div>
        </div>
    </div>
    @endif

    <!-- jQuery 3.1.1 -->
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.2.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/moment.js/2.15.1/moment.min.js"></script>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/bootstrap-datetimepicker/4.17.47/js/bootstrap-datetimepicker.min.js"></script>
    <script src="https://gitcdn.github.io/bootstrap-toggle/2.2.2/js/bootstrap-toggle.min.js"></script>
    <!-- AdminLTE App -->
    <script src="https://cdnjs.cloudflare.com/ajax/libs/admin-lte/2.4.3/js/adminlte.min.js"></script>

    <script src="https://cdnjs.cloudflare.com/ajax/libs/iCheck/1.0.2/icheck.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.5/js/select2.min.js"></script>

    @yield('scripts')
</body>
</html>

resources/views/layouts/datatables_css.blade.php
<!-- DataTable Bootstrap -->
<link href="https://cdn.datatables.net/1.10.19/css/dataTables.bootstrap.min.css" rel="stylesheet">
<link rel="stylesheet" href="https://cdn.datatables.net/buttons/1.3.1/css/buttons.bootstrap.min.css">

resources/views/layouts/datatables_js.blade.php
<!-- Datatables -->
<script src="https://cdn.datatables.net/1.10.19/js/jquery.dataTables.min.js"></script>
<script src="https://cdn.datatables.net/1.10.19/js/dataTables.bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.3.1/js/dataTables.buttons.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.3.1/js/buttons.bootstrap.min.js"></script>
<script src="https://cdn.datatables.net/buttons/1.3.1/js/buttons.colVis.min.js"></script>
<script src="{{ asset('vendor/datatables/buttons.server-side.js') }}"></script>

resources/views/layouts/menu.blade.php
<!--
<li class="{{ Request::is('empleados*') ? 'active' : '' }}">
    <a href="{!! route('empleados.index') !!}"><i class="fa fa-edit"></i><span>Empleados</span></a>
</li>-->
<li class="{{ Request::is('home*') ? 'active' : '' }}">
    <a href="{!! route('home') !!}"  style="color: white"><i class="fa fa-home"></i><span> Inicio</span></a>
</li>

<li class="{{ Request::is('empleadoRecategorizacions*') ? 'active' : '' }}">    
    <a href="{!! route('empleadoRecategorizacions.index') !!}" style="color: white"><i class="fa fa-edit"></i><span> Recategorizacion</span></a>
</li>

<hr>
@if(auth()->user()->role->name == 'administrador')
<div class="ac">
    
    <input class="ac-input" id="ac-tablas-aux" name="ac-1" type="checkbox" />
    <label class="ac-label" for="ac-tablas-aux" style="color:white"><i class="fa fa-angle-down"></i>Tablas Auxiliares</label>

    <article class="ac-text">

    <li class="{{ Request::is('regimens*') ? 'active' : '' }}">
        <a href="{!! route('regimens.index') !!}" class="ac-label"><i class="fa fa-edit"></i><span>Regimens</span></a>
    </li>

    <li class="{{ Request::is('agrupamientos*') ? 'active' : '' }}">
        <a href="{!! route('agrupamientos.index') !!}" class="ac-label"><i class="fa fa-edit"></i><span>Agrupamientos</span></a>
    </li>

    <li class="{{ Request::is('categorias*') ? 'active' : '' }}">
        <a href="{!! route('categorias.index') !!}" class="ac-label"><i class="fa fa-edit"></i><span>Categorias</span></a>
    </li>

    <li class="{{ Request::is('provincias*') ? 'active' : '' }}">
        <a href="{!! route('provincias.index') !!}" class="ac-label"><i class="fa fa-edit"></i><span>Provincias</span></a>
    </li>

    <li class="{{ Request::is('localidades*') ? 'active' : '' }}">
        <a href="{!! route('localidades.index') !!}" class="ac-label"><i class="fa fa-edit"></i><span>Localidades</span></a>
    </li>

    <li class="{{ Request::is('zonas*') ? 'active' : '' }}">
        <a href="{!! route('zonas.index') !!}" class="ac-label"><i class="fa fa-edit"></i><span>Zonas</span></a>
    </li>

    <li class="{{ Request::is('zonaLocalidads*') ? 'active' : '' }}">
        <a href="{!! route('zonaLocalidads.index') !!}" class="ac-label"><i class="fa fa-edit"></i><span>Zona Localidads</span></a>
    </li>
    <li class="{{ Request::is('titulos*') ? 'active' : '' }}">
        <a href="{!! route('titulos.index') !!}" class="ac-label"><i class="fa fa-edit"></i><span>Titulos</span></a>
    </li>

    </article>
</div>



<hr>
<div class="ac">
    <input class="ac-input" id="ac-usuarios" name="ac-1" type="checkbox" />
    <label class="ac-label" for="ac-usuarios" style="color:white"><i class="fa fa-angle-down"></i> Gestión de Usuarios</label>
    
    <article class="ac-text">
        <li class="{{ Request::is('usuarios*') ? 'active' : '' }}">
            <a href="{!! route('usuarios.index') !!}"  class="ac-label"><i class="fa fa-user a-menu"></i><span class="a-menu"> Usuarios</span></a>
        </li>

        <li class="{{ Request::is('rols*') ? 'active' : '' }}">
            <a href="{!! route('rols.index') !!}"  class="ac-label"><i class="fa fa-user a-menu"></i><span class="a-menu"> Roles</span></a>
        </li>

        <li class="{{ Request::is('permisos*') ? 'active' : '' }}">
            <a href="{!! route('permisos.index') !!}" class="ac-label"><i class="fa fa-user a-menu"></i><span class="a-menu"> Permisos</span></a>
        </li>

        <li class="{{ Request::is('permisoRols*') ? 'active' : '' }}">
            <a href="{!! route('permisoRols.index') !!}" class="ac-label"><i class="fa fa-user a-menu"></i><span class="a-menu"> Permisos Rol</span></a>
        </li>
    </article>
</div>

@endif

resources/views/layouts/sidebar.blade.php
<aside class="main-sidebar" id="sidebar-wrapper"  style="background-color: #3c8dbc">

    <!-- sidebar: style can be found in sidebar.less -->
    <section class="sidebar">

        <!-- Sidebar user panel (optional) -->
        <div class="user-panel">
            <!--<div class="pull-left image">
                <img src="{{asset('images/user.png')}}" class="img-circle"
                     alt="User Image"/>
            </div>
            <div class="pull-left info">
                @if (Auth::guest())
                <p>Función Pública</p>
                @else
                    <p><small>{{ Auth::user()->name}}</small></p>
                @endif-->
                <!-- Status -->
            <!--</div>-->
        </div>

        <!-- search form (Optional) -->
        <!--form action="#" method="get" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="q" class="form-control" placeholder="Search..."/>
          <span class="input-group-btn">
            <button type='submit' name='search' id='search-btn' class="btn btn-flat"><i class="fa fa-search"></i>
            </button>
          </span>
            </div>
        </form-->
        <!-- Sidebar Menu -->

        <ul class="sidebar-menu" data-widget="tree">
            @include('layouts.menu')
        </ul>
        <!-- /.sidebar-menu -->
    </section>
    <!-- /.sidebar -->
</aside>