routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');

Route::group(['middleware' => ['auth']], function () {
	Route::get('cambiar_contrasena','UsuariosController@cambiar_contrasena')->name('cambiar_contrasena');
	Route::post('cambiar_pass','UsuariosController@cambiar_pass')->name('cambiar_pass');
});

Route::group(['middleware' => ['auth', 'activo']], function () {	
	Route::get('/getAgrupamientos/{id}', 'EmpleadoRecategorizacionController@getAgrupamientos')->name('getAgrupamientos');
	Route::get('/getCategorias/{id}', 'EmpleadoRecategorizacionController@getCategorias')->name('getCategorias');

	Route::post('/calcular', 'EmpleadoRecategorizacionController@calcular')->name('empleadoRecategorizacions.calcular');

	Route::get('/descargar_recategorizacion', 'EmpleadoController@descargar_recategorizacion')->name('descargar_recategorizacion');
	Route::get('/imprimir_recategorizacion', 'EmpleadoController@imprimir_recategorizacion')->name('imprimir_recategorizacion');

	Route::resource('empleadoRecategorizacions', 'EmpleadoRecategorizacionController');

	Route::resource('empleados', 'EmpleadoController');

});

Route::group(['middleware' => ['auth', 'activo', 'role:administrador']], function () {

	Route::resource('agrupamientos', 'AgrupamientoController');

	Route::resource('categorias', 'CategoriaController');

	Route::resource('regimens', 'RegimenController');

	Route::resource('localidades', 'LocalidadesController');

	Route::resource('zonas', 'ZonasController');

	Route::resource('zonaLocalidads', 'ZonaLocalidadController');

	Route::resource('titulos', 'TituloController');

	Route::resource('usuarios', 'UsuariosController');

	Route::resource('rols', 'RolController');

	Route::resource('roleUsers', 'Role_UserController');

	Route::resource('usuarioOps', 'UsuarioOpController');

	Route::resource('permisos', 'PermisoController');

	Route::resource('permisoRols', 'PermisoRolController');

	Route::get('buscar_usuario', 'UsuariosController@buscar_usuario')->name('buscar_usuario');
	Route::get('buscar_usuario_resetear', 'UsuariosController@buscar_usuario_resetear')->name('buscar_usuario_resetear');
	
	Route::get('resetear_contrasena/{id}', 'UsuariosController@resetear_contrasena')->name('resetear_contrasena');

	Route::resource('provincias', 'ProvinciaController');

});

app/Http/Controllers/UsuariosController.php
<?php

namespace App\Http\Controllers;

use App\Http\Requests\CreateUsuariosRequest;
use App\Http\Requests\UpdateUsuariosRequest;
use App\Repositories\UsuariosRepository;
use App\Http\Controllers\AppBaseController;
use Illuminate\Http\Request;
use Flash;
use Response;
use DB;

use App\User;
use App\Role;
use App\Models\Role_User;

class UsuariosController extends AppBaseController
{
    /** @var  UsuariosRepository */
    private $usuariosRepository;

    public function __construct(UsuariosRepository $usuariosRepo)
    {
        $this->usuariosRepository = $usuariosRepo;
    }

    /**
     * Display a listing of the Usuarios.
     *
     * @param Request $request
     *
     * @return Response
     */
    public function index(Request $request)
    {
        $usuarios = User::orderBy('updated_at', 'desc')->paginate(20);

        return view('usuarios.index')
            ->with('usuarios', $usuarios)
            ->with('busqueda', $request->busqueda);
    }

    /**
     * Show the form for creating a new Usuarios.
     *
     * @return Response
     */
    public function create()
    {   
        $usuarios = null;
        $roles = Role::orderby('name', 'asc')->pluck('name', 'id');     
        return view('usuarios.create')
                    ->with('btn', 'crear')
                    ->with('usuarios', $usuarios)
                    ->with('roles', $roles);
    }

    /**
     * Store a newly created Usuarios in storage.
     *
     * @param CreateUsuariosRequest $request
     *
     * @return Response
     */
     public function store(CreateUsuariosRequest $request)
    {

        $input = $request->all();

        $password=$input['nro_dni'];
        $input['password'] = bcrypt($password);
        $input['name'] = $input['nombre'].' '.$input['apellido'];
        $nuevousuario = $input['nombre'][0].$input['apellido'];
        
        $user = User::where('usuario','like',$nuevousuario.'%')->get();
        $cantidad= count($user);
        if($cantidad > 0){
            $cantidad++;
            $input['usuario'] = strtolower($nuevousuario.$cantidad);
        }
        else{
            $input['usuario'] = strtolower($nuevousuario);
        }
        $usuarios = $this->usuariosRepository->create($input);

        Flash::success('El usuario '. $input['usuario'] .' se ha agregado correctamente.');

        return redirect(route('usuarios.index'));
    }

    /**
     * Display the specified Usuarios.
     *
     * @param int $id
     *
     * @return Response
     */
    public function show($id)
    {
        $usuario = $this->usuariosRepository->find($id);

        if (empty($usuario)) {
            Flash::error('Usuario no encontrado');

            return redirect(route('usuarios.index'));
        }

        $usuarios = Usuario::where('id_user', $usuario->id)->get();
        return view('usuarios.show')
                ->with('usuario', $usuario);
    }

    /**
     * Show the form for editing the specified Usuarios.
     *
     * @param int $id
     *
     * @return Response
     */
    public function edit($id)
    {
        $usuarios = $this->usuariosRepository->find($id);

        if (empty($usuarios)) {
            Flash::error('Usuarios not found');

            return redirect(route('usuarios.index'));
        }
        $roles = Role::orderby('name', 'asc')->pluck('name', 'id');     
        return view('usuarios.edit')->with('usuarios', $usuarios)
                    ->with('btn', 'editar')
                    ->with('roles', $roles);

    }

    /**
     * Update the specified Usuarios in storage.
     *
     * @param int $id
     * @param UpdateUsuariosRequest $request
     *
     * @return Response
     */
    public function update($id, UpdateUsuariosRequest $request)
    {
        $user = $this->usuariosRepository->find($id);
        if($request->usuario != $user->usuario){
            $validated = $request->validate([
                    'usuario' => 'required|unique:users',
            ]);
        }
        if (empty($user)) {
            Flash::error('Usuarios not found');

            return redirect(route('usuarios.index'));
        }
        
        $input=$request->all();

        $usuarios = $this->usuariosRepository->update($input, $id);

        Flash::success('Usuarios actualizado correctamente.');

        return redirect(route('usuarios.index'));
    }

    /**
     * Remove the specified Usuarios from storage.
     *
     * @param int $id
     *
     * @throws \Exception
     *
     * @return Response
     */
    public function destroy($id)
    {
        $usuarios = $this->usuariosRepository->find($id);

        if (empty($usuarios)) {
            Flash::error('Usuarios not found');

            return redirect(route('usuarios.index'));
        }

        $this->usuariosRepository->delete($id);
        
        Flash::success('Usuarios eliminado correctamente.');

        return redirect(route('usuarios.index'));
    }

    public function cambiar_contrasena(){        
        return view('usuarios.cambiar_contrasena');
    }

    public function cambiar_pass(Request $request){
        //dd($request->password_viejo);
        $id = auth()->user()->id;
        $user = User::where('id', $id)->first();
        $password = $user->password;

        
        if (password_verify($request->password_viejo, $password)) {
           if(strlen($request->password_nuevo)>= 8) {
               if($request->password_nuevo == $request->password_viejo){
                    Flash::error('La contraseña nueva no puede ser igual a la contraseña actual');
                    return view('usuarios.cambiar_contrasena');
               }
               else if($request->password_nuevo == $request->password_repetido){
                    $password = bcrypt($request->password_nuevo);
                    User::where('id', $id)->update(array('password'=>$password, 'activo'=>1));
                    Flash::success('El cambio de contraseña fue existoso');
                    return redirect(route('home'));
                }
                else {
                    Flash::error('La nueva contraseña no coincide');
                    return view('usuarios.cambiar_contrasena');
                }
            }
           else {
            Flash::error('La nueva contraseña debe tener al menos 8 caracteres.');
            return view('usuarios.cambiar_contrasena');
            }
        }
        else {
            Flash::error('La contraseña actual ingresada no coincide.');
            return view('usuarios.cambiar_contrasena');
        }

    }

    public function resetear_contrasena($id){
        $user = User::where('id', $id)->first();
        $password = bcrypt($user->nro_dni);
        User::where('id', $id)->update(array('password'=>$password, 'activo'=>0));
        Flash::success('La contraseña ha sido reseteada correctamente.');
        
        $usuarios = User::orderBy('name', 'asc')->paginate(20);
        return redirect(route('usuarios.index'));
    }

    public function buscar_usuario(Request $request){
        $usuarios = User::select('users.*')
                        ->where('name', 'like', '%'.$request->busqueda.'%')
                        ->orWhere('nro_dni', 'like', '%'.$request->busqueda.'%')
                        ->orWhere('usuario', 'like', '%'.$request->busqueda.'%') 
                        ->orWhere('email', 'like', '%'.$request->busqueda.'%') 
                        ->orderBy('name', 'asc')
                        ->paginate(20);
       
        return view('usuarios.index')
                ->with('usuarios', $usuarios)
                ->with('busqueda', $request->busqueda);
    }

    public function buscar_usuario_resetear(Request $request){
        $usuarios = User::where('name', 'like', '%'.$request->busqueda.'%')
                        ->orWhere('nro_dni', 'like', '%'.$request->busqueda.'%')
                        ->orWhere('usuario', 'like', '%'.$request->busqueda.'%') 
                        ->orderBy('name', 'asc')
                        ->paginate(20);
       
        return view('usuarios.resetear')
                ->with('usuarios', $usuarios)
                ->with('busqueda', $request->busqueda);;
    }

}

resources/views/usuarios/cambiar_contrasena.blade.php
@extends('layouts.app')

@section('content')
@include('flash::message')
    <section class="content-header">
        <h1>
            Cambiar contraseña
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">

{!! Form::open(array('url' => 'cambiar_pass')) !!}
						<div class="form-group col-sm-12">
							<div class="form-group col-sm-4">
			    				{!! Form::label('password_viejo', 'Contraseña actual:') !!}
			    				{!! Form::password('password_viejo', ['class' => 'form-control']) !!}
							</div>
						</div>

						<div class="form-group col-sm-12">
							<div class="form-group col-sm-4">
			    				{!! Form::label('password_nuevo', 'Nueva contraseña:') !!}
			    				{!! Form::password('password_nuevo', ['class' => 'form-control']) !!}
							</div>
						</div>
						
						<div class="form-group col-sm-12">
							<div class="form-group col-sm-4">
			    				{!! Form::label('confirmar_password', 'Confirmar contraseña:') !!}
			    				{!! Form::password('password_repetido', ['class' => 'form-control']) !!}
							</div>
						</div>
						<!-- Submit Field -->
						<div class="form-group col-sm-4 text-center">
						<br>
	    					{!! Form::submit('Guardar', ['class' => 'btn btn-primary']) !!}
	    					<a href="{!! route('home') !!}" class="btn btn-default">Cancelar</a>
						</div>
            {!! Form::close() !!}
				</div>
            </div>
        </div>
    </div>
@endsection

resources/views/usuarios/create.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Crear Usuarios
        </h1>
    </section>
    <div class="content">
        @include('adminlte-templates::common.errors')
        <div class="box box-primary">

            <div class="box-body">
                <div class="row">
                    {!! Form::open(['route' => 'usuarios.store']) !!}
                        @include('flash::message')
                        @include('usuarios.fields')

                    {!! Form::close() !!}
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/usuarios/edit.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            Editar Usuarios
        </h1>
   </section>
   <div class="content">
       @include('adminlte-templates::common.errors')
       <div class="box box-primary">
           <div class="box-body">
               <div class="row">
                   {!! Form::model($usuarios, ['route' => ['usuarios.update', $usuarios->id], 'method' => 'patch']) !!}
                        @include('flash::message')

                        @include('usuarios.fields')

                   {!! Form::close() !!}
               </div>
           </div>
       </div>
   </div>
@endsection

resources/views/usuarios/fields.blade.php
<!-- Name Field -->
@if($btn =='crear')
<div class="form-group col-sm-6">
    {!! Form::label('nombre', 'Nombre:') !!}
    {!! Form::text('nombre', null, ['class' => 'form-control', 'maxlength' => '90', 'required' => '']) !!}
</div>
<div class="form-group col-sm-6">
    {!! Form::label('apellido', 'Apellido:') !!}
    {!! Form::text('apellido', null, ['class' => 'form-control', 'maxlength' => '100', 'required' => '']) !!}
</div>
@else
<div class="form-group col-sm-6">
    {!! Form::label('name', 'Nombre y Apellido:') !!}
    {!! Form::text('name', null, ['class' => 'form-control', 'maxlength' => '191', 'required' => '']) !!}
</div>

<div class="form-group col-sm-6">
    {!! Form::label('usuario', 'Usuario:') !!}
    {!! Form::text('usuario', null, ['class' => 'form-control', 'maxlength' => '191', 'required' => '']) !!}
</div>
@endif

<!-- Email Field -->
<div class="form-group col-sm-6">
    {!! Form::label('email', 'Email:') !!}
    {!! Form::email('email', null, ['class' => 'form-control', 'maxlength' => '191']) !!}
</div>

@if($btn =='crear')
<!-- Password Field -->
    {!! Form::hidden('password', 12345678, ['class' => 'form-control']) !!}
    {!! Form::hidden('activo', 0, ['class' => 'form-control']) !!}
@else
    {!! Form::hidden('password', $usuarios->password, ['class' => 'form-control']) !!}
    {!! Form::hidden('activo', $usuarios->activo, ['class' => 'form-control']) !!}
@endif

<!-- Nro Dni Field -->
<div class="form-group col-sm-6">
    {!! Form::label('nro_dni', 'Nro Documento:') !!}
    {!! Form::number('nro_dni', null, ['class' => 'form-control']) !!}
</div>

<!-- Id Tipo Dni Field -->
<div class="form-group col-sm-6">
    {!! Form::label('id_rol', 'Rol:') !!}
    {!! Form::select('id_rol', $roles, null, ['class' => 'form-control', 'placeholder' => 'Seleccionar']) !!}
</div>

<!-- Submit Field -->
<div class="form-group col-sm-12">
    {!! Form::submit('Guardar', ['class' => 'btn btn-primary']) !!}
    <a href="{!! route('usuarios.index') !!}" class="btn btn-default">Cancelar</a>
</div>

resources/views/usuarios/index.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1 class="pull-left">Usuarios</h1>
        <h1 class="pull-right">
           <a class="btn btn-primary" style="margin-top: -10px;margin-bottom: 5px" href="{!! route('usuarios.create') !!}">Agregar Nuevo</a>

        </h1>
    </section>
    <div class="content">
        <div class="clearfix"></div>

        @include('flash::message')

        <div class="clearfix"></div>
        <div class="box box-primary">
            <div class="box-body">
                    @include('usuarios.table')
            </div>
        </div>
        <div class="text-center">
        
        </div>
    </div>
@endsection

resources/views/usuarios/show.blade.php
@extends('layouts.app')

@section('content')
    <section class="content-header">
        <h1>
            {!! $usuario->id !!} - Usuario: {!! $usuario->usuario !!}
        </h1>
    </section>
    <div class="content">
        <div class="box box-primary">
            <div class="box-body">
                <div class="row" style="padding-left: 20px">
                    @include('usuarios.show_fields')
                    <a href="{!! route('usuarios.index') !!}" class="btn btn-primary">Volver</a>
                </div>
            </div>
        </div>
    </div>
@endsection

resources/views/usuarios/show_fields.blade.php
<h4><b>{{ $usuario->usuario }}</b></h4>

<!-- Name Field -->
<div class="form-group col-sm-4">
    {!! Form::label('name', 'Nombre:') !!}
    <p>{!! $usuario->name !!}</p>
</div>

<!-- Nro Dni Field -->
<div class="form-group col-sm-4">
    {!! Form::label('nro_dni', 'Tipo y Nro de Documento:') !!}
    <p>{!! $usuario->tipo_dni->tipo !!}: {!! $usuario->nro_dni !!}</p>
</div>

<!-- Email Field -->
<div class="form-group col-sm-4">
    {!! Form::label('email', 'Email:') !!}
    <p>{!! $usuario->email !!}</p>
</div>

@if($usuario->op != null)
<!-- Id Op Cobra Field -->
<div class="form-group col-sm-4">
    {!! Form::label('id_op_cobra', 'Id Op Cobra:') !!}
    <p>{!! $usuario->op->descripcion !!}</p>
</div>
@endif

@if($usuario->role != null)
<!-- Id Op Cobra Field -->
<div class="form-group col-sm-8">
    {!! Form::label('id_rol', 'Rol:') !!}
    <p>{!! $usuario->role->name !!}</p>
</div>
@else
<div class="form-group col-sm-4">
    {!! Form::label('id_rol', 'Rol:') !!}
    <p>{!! $usuario->id_rol !!}</p>
</div>
@endif

<hr>

<div class="form-group col-sm-12">

@if($usuario->activo == false)
    <b>Activo: </b> No
@else
    <b>Activo: </b> Si
@endif
<br>
@if($usuario->habilitado == false)
    <b>Habilitado: </b> No
@else
    <b>Habilitado: </b> Si
@endif
</div>

<div class="form-group col-sm-12">
    @if($usuario->activo == false)
        <p><b>Usuario inactivo:</b> El usuario aún no se ha logueado por primera vez o se le ha hecho un reseteo de la contraseña. El usuario solo tendrá permiso para loguearse y cambiar la contraseña.</p>
    @elseif($usuario->habilitado == false)
        <p><b>Usuario Inhabilitado:</b> Los permisos de creación/edición y eliminación que tenga el rol serán revocados para el usuario. Solo tendrá permiso de Lectura.</p>
    @else
        <p><b>Usuario Habilitado: </b>El usuario tiene todos los permisos del rol.</p>         
    @endif
</div>

<div class="form-group col-sm-12">

<h4><b>Ordenes de Pago asociadas  </b><a href="{!! route('usuarioOps.edit', [$usuario->id]) !!}" class='btn btn-primary  btn-xs'>Editar</a></h4>
</div>

<div class="form-group col-sm-12">
    @foreach($usuario_ops as $uop)    
    <div class="form-group col-sm-4">
        {{$uop->id_op}} - {{ $uop->op->descripcion}}
    </div>
    @endforeach

</div>

resources/views/usuarios/table.blade.php
<form action="{!! route('buscar_usuario') !!}" method="GET" class="sidebar-form">
            <div class="input-group">
                <input type="text" name="busqueda" class="form-control" placeholder="Buscar por documento o nombre y apellido"/ style="background-color: white">
          <span class="input-group-btn">
            <button type='submit' id='search-btn' class="btn btn-flat" style="background-color: white"><i class="fa fa-search"></i>
            </button>
          </span>
            </div>
        </form>


<div class="table table-responsive">
    <table class="table" id="usuarios-table">
        <thead>
            <tr>
                <th>Usuario</th>
                <th>Nro Dni</th>
                <th>Nombre y Apellido</th>
                <th>Email</th>
                <th>Rol</th>
                <th>Activo</th>
            </tr>
        </thead>
        <tbody>
        @foreach($usuarios as $usuario)
            <tr>
                <td>{!! $usuario->usuario !!}</td>
                <td>{!! $usuario->nro_dni !!}</td>
                <td>{!! $usuario->name !!}</td>
                <td>{!! $usuario->email !!}</td>
                @if ($usuario->role != NULL)
                <td>{!! $usuario->role->name !!}
                @else
                <td></td>
                @endif
                <td>@if($usuario->activo == false)
                 Inactivo
                 @else
                 Activo
                 @endif
                </td>

                <td>
                    <a href="{!! route('usuarios.edit', [$usuario->id]) !!}" class='btn btn-block btn-primary btn-xs'>Editar</a>
                    {!! Form::open(['route' => ['usuarios.destroy', $usuario->id], 'method' => 'delete']) !!}
                        {!! Form::button('Eliminar', ['type' => 'submit', 'class' => 'btn btn-block btn btn-danger btn-xs', 'onclick' => "return confirm('¿Está seguro?')"]) !!}
                    {!! Form::close() !!}

                    {!! Form::open(['route' => ['resetear_contrasena', $usuario->id], 'method' => 'get']) !!}
                    {!! Form::button('Resetear', ['type' => 'submit', 'class' => 'btn btn-block btn btn-warning btn-xs', 'onclick' => "return confirm('¿Está seguro de reestablecer la contraseña?')"]) !!}
                            {!! Form::close() !!}
                </td>
            </tr>
        @endforeach
        </tbody>
    </table>

</div>

{!! $usuarios->appends(['busqueda'=>$busqueda])->links() !!}